image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - ols-web/target/ols-boot.war
      - ols-apps/ols-config-importer/target/ols-config-importer.jar
      - ols-apps/ols-loading-app/target/ols-indexer.jar
      - ols-solr/src/main/solr-5-config

docker-build:
  stage: package
  script:
  - docker build -t ebispot/ols:3.3.$CI_PROJECT_BUILDS .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push ebispot/ols:3.3.$CI_PROJECT_BUILDS

