name: OBO Foundry
title: The OBO Foundry
markdown: kramdown
highlighter: rouge
baseurl: /
imgurl: /images
repo: https://github.com/OBOFoundry/OBOFoundry.github.io/
repo_src: https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/
author:
  name: OBO Technical WG
ontologies:
  - activity_status: active
    build: {checkout: 'git clone https://github.com/EBISPOT/duo.git', path: ., system: git}
    contact: {email: mcourtot@gmail.com, github: mcourtot, label: Melanie Courtot}
    dependencies:
      - {id: iao}
      - {id: bfo}
    description: DUO is an ontology which represent data use conditions.
    homepage: https://github.com/EBISPOT/DUO
    id: duo
    jobs:
      - {id: 'https://travis-ci.org/EBISPOT/DUO', type: travis-ci}
    layout: ontology_detail
    license: {label: CC-BY, logo: 'http://mirrors.creativecommons.org/presskit/buttons/80x15/png/by.png',
              url: 'http://creativecommons.org/licenses/by/3.0/'}
    ontology_purl: http://purl.obolibrary.org/obo/duo.owl
    products:
      - {id: duo.owl, ontology_purl: 'http://purl.obolibrary.org/obo/duo.owl'}
    title: The Data Use Ontology
    tracker: https://github.com/EBISPOT/DUO/issues
    preferred_root_term:
      - http://purl.obolibrary.org/obo/DUO_0000001
      - http://purl.obolibrary.org/obo/DUO_0000017
      - http://purl.obolibrary.org/obo/OBI_0000066
    classification:
      - DFG: 
          - 4.2.2
          - 3.5
      - GBV: 
          - test
          - test5
      - collection:
          - NFDI4ING
          - CoyPu
      - {subject: ["Information Science","Management Information Systems"],subfield: ["System Analysis","System Design"]}
  - preferredPrefix: aeon
    creator:
      - Christian Hauschke
      - Christoph Lange
      - Michael Conlon
      - Philip Strömert
    ontology_purl: https://raw.githubusercontent.com/tibonto/aeon/main/aeon.owl
    description: The Academic Event Ontology (AEON) is used to represent information regarding academic events. The ontology supports the identification, development, management, evaluation, and impact assessment of events, components of events and event series, as well as identification and reuse of works presented or developed at events. The ontology is independent of knowledge, creative domain, or topics related to events. AEON is focused on events and assumes the representation of many entities associated with events such as attendees, locations, academic works, datetimes, and processes are defined in compatible ontologies.
    id: aeon
    license: {url: 'https://creativecommons.org/licenses/by/4.0/'}
    title: Academic Event Ontology@en
    classification:
        - DFG: 
            - 4.4.1
            - 3.2.5
        - GBV: 
            - test
            - test2
        - collection:
            - NFDI4CULTURE
        - {subject: ["Management and Organization", "Event Management"], subfield: ["Academic Affairs","Congress Organization"]}
  - id: mondo
    ontology_purl: http://purl.obolibrary.org/obo/mondo.obo
    classification:
      - DFG: 
          - 3.2.2
          - 1.4
      - GBV: 
          - test4
          - test5
          - test2
      - collection:
          - NFDI4ING
          - NFDI4CHEM
      - subject:
          - Epidemiology
  - activity_status: active
    contact:
      email: siiraa@umich.edu
      label: Sirarat Sarntivijai
    dependencies:
      - id: uberon
      - id: cl
      - id: doid
      - id: ncbitaxon
    description: An ontology to standardize and integrate cell line information and
      to support computer-assisted reasoning.
    homepage: http://www.clo-ontology.org
    id: clo
    layout: ontology_detail
    license:
      label: CC-BY
      logo: http://mirrors.creativecommons.org/presskit/buttons/80x15/png/by.png
      url: http://creativecommons.org/licenses/by/3.0/
    ontology_purl: http://purl.obolibrary.org/obo/clo.owl
    products:
      - id: clo.owl
        ontology_purl: http://purl.obolibrary.org/obo/clo.owl
    title: Cell Line Ontology
    tracker: https://github.com/CLO-Ontology/CLO/issues
  - activity_status: active
    build:
      checkout: git clone https://github.com/Superraptor/GSSO.git
      path: .
      system: git
    contact:
      email: kronkcj@mail.uc.edu
      github: Superraptor
      label: Clair Kronk
      orcid: 0000-0001-8397-8810
    description: The Gender, Sex, and Sexual Orientation (GSSO) ontology has terms for
      annotating interdisciplinary information concerning gender, sex, and sexual orientation
      for primary usage in the biomedical and adjacent sciences.
    domain: organisms
    homepage: https://gsso.research.cchmc.org/
    id: gsso
    layout: ontology_detail
    license:
      label: Apache 2.0 License
      url: http://www.apache.org/licenses/LICENSE-2.0
    ontology_purl: http://purl.obolibrary.org/obo/gsso.owl
    preferredPrefix: GSSO
    products:
    - id: gsso.owl
      ontology_purl: http://purl.obolibrary.org/obo/gsso.owl
    - id: gsso.obo
      ontology_purl: http://purl.obolibrary.org/obo/gsso.obo
    - id: gsso.json
      ontology_purl: http://purl.obolibrary.org/obo/gsso.json
    repository: https://github.com/Superraptor/GSSO
    title: Gender, Sex, and Sexual Orientation (GSSO) ontology
    tracker: https://github.com/Superraptor/GSSO/issues
  - activity_status: active
    contact:
      email: davidos@ebi.ac.uk
      github: dosumis
      label: David Osumi-Sutherland
      orcid: 0000-0002-7073-9172
    dependencies:
    - id: pr
    - id: go
    - id: uberon
    - id: ro
    - id: pato
    - id: ncbitaxon
    - id: bfo
    - id: cl
    - id: omo
    - id: nbo
    - id: chebi
    - id: so
    description: Cell types that are provisionally defined by experimental techniques
      such as single cell or single nucleus transcriptomics rather than a straightforward
      & coherent set of properties.
    domain: phenotype
    homepage: https://github.com/obophenotype/provisional_cell_ontology
    id: pcl
    layout: ontology_detail
    license:
      label: CC BY 4.0
      logo: http://mirrors.creativecommons.org/presskit/buttons/80x15/png/by.png
      url: http://creativecommons.org/licenses/by/4.0/
    ontology_purl: http://purl.obolibrary.org/obo/pcl.owl
    preferredPrefix: PCL
    products:
    - id: pcl.owl
      ontology_purl: http://purl.obolibrary.org/obo/pcl.owl
    - id: pcl.obo
      ontology_purl: http://purl.obolibrary.org/obo/pcl.obo
    - id: pcl.json
      ontology_purl: http://purl.obolibrary.org/obo/pcl.json
    - id: pcl-base.owl
      ontology_purl: http://purl.obolibrary.org/obo/pcl-base.owl
    - id: pcl-base.obo
      ontology_purl: http://purl.obolibrary.org/obo/pcl-base.obo
    - id: pcl-base.json
      ontology_purl: http://purl.obolibrary.org/obo/pcl-base.json
    - id: pcl-full.owl
      ontology_purl: http://purl.obolibrary.org/obo/pcl-full.owl
    - id: pcl-full.obo
      ontology_purl: http://purl.obolibrary.org/obo/pcl-full.obo
    - id: pcl-full.json
      ontology_purl: http://purl.obolibrary.org/obo/pcl-full.json
    - id: pcl-simple.owl
      ontology_purl: http://purl.obolibrary.org/obo/pcl-simple.owl
    - id: pcl-simple.obo
      ontology_purl: http://purl.obolibrary.org/obo/pcl-simple.obo
    - id: pcl-simple.json
      ontology_purl: http://purl.obolibrary.org/obo/pcl-simple.json
    repository: https://github.com/obophenotype/provisional_cell_ontology
    title: Provisional Cell Ontology
    tracker: https://github.com/obophenotype/provisional_cell_ontology/issues
  - activity_status: active
    build:
      checkout: git clone https://github.com/scdodev/scdo-ontology.git
      path: .
      system: git
    contact:
      email: giant.plankton@gmail.com
      github: JadeHotchkiss
      label: Jade Hotchkiss
      orcid: 0000-0002-2193-0704
    dependencies:
    - id: apollo_sv
    - id: aro
    - id: chebi
    - id: chmo
    - id: cmo
    - id: doid
    - id: dron
    - id: duo
    - id: envo
    - id: eupath
    - id: exo
    - id: gaz
    - id: gsso
    - id: hp
    - id: hsapdv
    - id: ico
    - id: ido
    - id: idomal
    - id: mp
    - id: nbo
    - id: ncit
    - id: obi
    - id: ogms
    - id: opmi
    - id: pr
    - id: sbo
    - id: stato
    - id: symp
    - id: uo
    - id: vo
    - id: vt
    description: An ontology for the standardization of terminology and integration
      of knowledge about Sickle Cell Disease.
    domain: disease
    homepage: https://scdontology.h3abionet.org/
    id: scdo
    layout: ontology_detail
    license:
      label: GPL-3.0
      url: https://www.gnu.org/licenses/gpl-3.0.en.html
    ontology_purl: https://github.com/scdodev/scdo-ontology/blob/master/scdo_fr-t-en.owl
    preferredPrefix: SCDO
    products:
    - id: scdo.owl
      ontology_purl: http://purl.obolibrary.org/obo/scdo.owl
    - id: scdo.obo
      ontology_purl: http://purl.obolibrary.org/obo/scdo.obo
    repository: https://github.com/scdodev/scdo-ontology
    title: Sickle Cell Disease Ontology
    tracker: https://github.com/scdodev/scdo-ontology/issues
