"@context":

ontologies:
  - id: ncbitaxon
    base_uri:
     - http://purl.obolibrary.org/obo/NCBITaxon_

## DUO override
  - id: duo
    ontology_purl: http://purl.obolibrary.org/obo/duo.owl
    preferred_root_term:
      - http://purl.obolibrary.org/obo/DUO_0000001
      - http://purl.obolibrary.org/obo/DUO_0000017
      - http://purl.obolibrary.org/obo/OBI_0000066
